### ISSUE TITLE
Feature File for generating results

### ISSUE THREAD

**Issue by Zirsha** [MKLab-ITI/FIVR-200K#3]
Hi! i am following instructions given in repository but facing difficulty while passing arguments to calculate_similarities.py. It is taking features file as input. Can you please guide me how i can extract global features of each video in dataset. evaluation.py needs this result file for evaluation.
Thanks

**Comment by gkordo** [comment]
Hi Zirsha.
We provide the extracted CNN and 3DCNN features for each method/run [here](http://ndd.iti.gr/features/). You can use one of these as input to `calculate_similarities.py`. 

Otherwise, you may provide your own feature file that contains one feature vector for each video. Keep in mind that the ordering of the videos in the provided file **must** be according to  [youtube_ids.txt](https://github.com/MKLab-ITI/FIVR-200K/blob/master/dataset/youtube_ids.txt).

Finally, it is not mandatory to use the `calculate_similarities.py` to generate the result file. The evaluation script will work if you provide a file that has structure as described in [step 1](https://github.com/MKLab-ITI/FIVR-200K#evaluation) in the Evaluation section.

**Comment by Zirsha** [comment]
It is working ! Thank you. But i need to test it on other videos as well. Can you please share the code of feature extraction.

**Comment by gkordo** [comment]
No prob! Of course I can. Have a look at our repository for the extraction of [intermediate CNN features](https://github.com/MKLab-ITI/intermediate-cnn-features). I close the issue since it has been resolved.
